#name: try { ... try { ... } finally { ... } } catch { ... }
# --
try {
     ${1:Object} ${2:o} = null;
     try {
          $0
     } finally {
          $2.close();
     }
} catch (${3:Exception e}) {
     // TODO: Handle this exception
}